### ISSUE TITLE
[Share] ReplyPersistenceTest 테스트 실패

### ISSUE THREAD

**Issue by pbg0205** [soolsul/soolsul-server#103]
## 🙋🏻‍♂️ 공유 사항
![image](https://user-images.githubusercontent.com/48561660/206729305-efd7740c-6915-4d51-8551-1b7075366b34.png)
- ReplyPersistenceTest 테스트 실패하고 있어서 검토 부탁합니다 😃

## 📖 참고 사항
공유할 내용, 레퍼런스, 추가로 발생할 것으로 예상되는 이슈, 스크린샷 등을 넣어 주세요.
- 추가적으로 필요한 내용은 comment로 남겨주세요.

**Comment by zbqmgldjfh** [comment]
음 일단 저의 컴에서는 정상적으로 통과 되고 있어서, 혹시 어떤 에러가 발생하는중이신가요??
<img width="410" alt="image" src="https://user-images.githubusercontent.com/60593969/206889396-ba817737-ea6c-4755-a250-a91afdb005c7.png">

**Comment by pbg0205** [comment]
containesExactly 에서 값이 다른 예외 메세지가 반환되고 있어요~
저녁에 관련 내용 이미지 첨부해서 공유드릴게요

**Comment by pbg0205** [comment]
![image](https://user-images.githubusercontent.com/48561660/207065881-0ff9e942-0f81-4c79-a887-f217a899e752.png)

- 이렇게 출력되고 있어요!

**Comment by zbqmgldjfh** [comment]
음? 제쪽에서는 계속 정상으로 수행되고 있습니다 ㅠ,ㅠ, 브렌치가 최신 dev이신거죠??

**Comment by pbg0205** [comment]
넵 맞아요~ 근데 또 지금은 정상 동작하고 있어요🫢
