### ISSUE TITLE
[Feat] Test Container 적용하기

### ISSUE THREAD

**Issue by zbqmgldjfh** [soolsul/soolsul-server#111]
## 💡 개요
지금은 CI를 하는 과정에서 EC2만 있고, DB가 없어 AWS상에서 테스트가 실패하게 된다.
테스트를 위한 RDB를 별도로 사용하기 보다는, Test Container라는 Docker 기반의 Tool을 적용시켜보자!

## 🤩 기능 설명
Test용 DB

## 🍒 세부 기능
어떤 세부 기능을 구현할지 말씀해주세요.
- [x] Test Container 적용

## 📖 참고 사항
- 백기선님 설명 영상 (https://www.inflearn.com/course/the-java-application-test/unit/28674)
- https://wedul.site/649

**Comment by pbg0205** [comment]
크....감사합니다 👍👍👍
