### ISSUE TITLE
[Bug] compileTestJava 수행시 롬복 문제 발생

### ISSUE THREAD

**Issue by zbqmgldjfh** [soolsul/soolsul-server#113]
## ❌ 버그 발생
빌드는 되는데, 빌드 후 compileTestJava를 수행할 때 기본 생성자가 없다는 오류가 발생합니다.
롬복 RequiredArgsConstructor을 제거한후 직접 생성자를 명시하면 해결 되기는 하는데, 롬복이 안먹히는것 같은데 이유는 모르겠습니다??

## 🐞 발생한 위치
<img width="1324" alt="image" src="https://user-images.githubusercontent.com/60593969/206995067-1321f7bf-45a4-4f29-8afb-5f0551a1c4cb.png">

**Comment by pbg0205** [comment]
음... 오늘 저녁에 일정이 있어서 갔다와서 재현되는지 확인해볼게요

**Comment by pbg0205** [comment]
![image](https://user-images.githubusercontent.com/48561660/207067824-2fec227d-fc69-4d31-987f-706633bfb5e5.png)
재현 해보려고 하는데 계속 정상 동작하네요
혹시 build 파일 제거하고 다시 빌드해도 동일 현상 재현되나요??

**Comment by zbqmgldjfh** [comment]
아 이거 일단 롬복 제거하고 수정해서 merge해버려서 작동하는것 같습니다 ㅎㅎ
