### ISSUE TITLE
[Feat] OSIV false설정으로 DB커넥션을 작게 유지하고 응답성 높히기

### ISSUE THREAD

**Issue by zbqmgldjfh** [soolsul/soolsul-server#138]
## 🍒 세부 기능
어떤 세부 기능을 구현할지 말씀해주세요.
- [x] OSIV off 설정

## 📖 참고 사항
https://blogshine.tistory.com/550

**Comment by pbg0205** [comment]
open-session-in-view 부분은 `spring.jpa.open-in-view=false` 로 변경하면 `OpenSessionEntityManagerInterceptor`가 비활성화되서 영속성 컨텍스트 범위가 `@Transactional` 단위로 동작할거에요. 현재 저희 구조상 Facade 에 @Transactional 어노테이션을 처리하고 있어서 정상 동작할거에요~

**Comment by pbg0205** [comment]
OpenSessionEntityManagerInterceptor 코드 확인해보면 아마 EntityManager(Factory) 의존성 주입하는 형태로 구현되어 있을텐데 겸사겸사 확인해보시면 좋을 것 같습니다!

**Comment by zbqmgldjfh** [comment]
오 OpenSessionEntityManagerInterceptor부분 한번 확인해보겠습니다!!
물론 사용자는 없지만 ㅋㅋㅋ 마침 저희가 CQRS가 적용되있기도 하고, 응답성 높히기에 적합하다 생각하여 옵션만 바꿔볼려 하였습니다 ㅋㅋㅋ
고민거리를 하나라도 더 이슈로 남기기 위해 ㅎㅎ!
답변 감사합니닷!!

**Comment by pbg0205** [comment]
OpenSessionEntityManagerInterceptor 가 아니라 `OpenEntityManagerInViewInterceptor` 였어요!
