### ISSUE TITLE
[Suggest] Photos 일급 컬렉션 사용 건의

### ISSUE THREAD

**Issue by zbqmgldjfh** [soolsul/soolsul-server#15]
## 🙋🏻‍♂️ 제안 사항
상요중인 Photo들을 단일 컬렉션으로 가지고 있는 1급 컬렉션으로 Photos를 사용하는 방법을 건의 합니다.

예를 들어 Post에는 다음과 같이 작업될 것 입니다
```Java
@Embeddable
@NoArgsConstructor(access = AccessLevel.PROTECTED)
public class PostPhotos {

    private static final int LIMIT_SIZE = 10;

    @ElementCollection
    @CollectionTable(
            name = "post_photos",
            joinColumns = @JoinColumn(name = "uuid")
    )
    @OrderColumn
    private List<PostPhoto> postPhotos;

    // 생성자나 일부 생략
}
```
다행이 사진들을 분리한 상태라서 Post 에그리거트 에서는 PostPhoto를 연관관계를 통해 사용하면 될것 같습니다!
또한 Post 자신의 에그리거트 집합안에 있는 대상이라 연관관계를 사용해도 될것 같습니다!
연관된 객체를 한번에 관리하고 있기 때문에 일종의 배치작업 메서드를 만들어 일괄적으로 적용하기 쉬우며, 외부에서 쉽게 변경하지 못하도록 막아주기도 합니다.

나머지 단건사진들도 이런식으로 사용하면 어떨까? 해서요!

## 📖 참고 사항
공유할 내용, 레퍼런스, 추가로 발생할 것으로 예상되는 이슈, 스크린샷 등을 넣어 주세요.
- 추가적으로 필요한 내용은 comment로 남겨주세요.

**Comment by gusckd57** [comment]
https://www.nowwatersblog.com/jpa/ch14/14-1
사실 빠르게 하려면 이렇게 하는 것도 나쁘지 않긴한데
전 그냥 중간테이블 놓고 원투 매니로 하는 게 더ㅠ낫지 않을까 싶어요.

**Comment by gusckd57** [comment]
저희가 통제할 수 있는 컬럼이 있어야 나중에 쿼리dsl에서도 조건으로 사용할 수 있구요

**Comment by gusckd57** [comment]
일급컬렉션 자체는 너무 좋은 것 같습니다. 생각해보지 못한 방식이네요

**Comment by pbg0205** [comment]
이번에 `@ElementCollection` 어노테이션과 `@OrderColumn`은 처음 봤는데 값 객체로 신기하네요 😃
일급 컬렉션 방식은 정말 좋은 것 같아요. 상태와 행위를 한 곳에서 관리할 수 있는 장점은 정말 크다고 생각해요!
하지만 만약에 일급 컬렉션을 사용하면 다른 방법으로 고민해봐야할 것 같아요. 궁금해서 한번 찾아봤는데 `@ElementCollection`은 아래와 같은 문제가 있을 수 있다고 하네요.

- `@ElementCollection`을 사용하면 별도의 **식별자(PK)를 선언하지 않기 때문에 변경을 추적하기 어렵다**고 해요ㅠ 저희가 JPA를 사용하는데 있어 장점 중의 하나인 dirty checking 을 활용할 수 없는 경우도 있을 수 있을 것 같아요.
- 값 컬렉션에는 데이터 추가, 삭제가 동작 시, 엔티티의 연관된 데이터를 모두 삭제하고 다시 insert 문을 추가하는 방식으로 동작해서 **예상하지 못한 상태의 쿼리를 작성**할 수 있다고 하네요. 그리고 `@ElementCollection` 과 `@OrderColumn ` 을 함께 사용하면 **@OrderColumn 을 매핑하지 못해** 데이터 추가 시에 순서를 관리하는 컬럼이 저장되지 않는 단점이 있다고 합니다. 아래에 참고한 내용 공유드려요ㅎㅎ
   - https://www.nowwatersblog.com/jpa/ch14/14-1
   - https://developer-hm.tistory.com/48

일급 컬렉션을 활용하는 방법에 대해 고민해봤는데 @OneToMany 연관관계를 일급 컬렉션으로 사용해서 활용할 수 있을 것 같아요. 그럴 경우에 두 엔티티 모두 영속성 컨텍스트의 관리대상이 되서 변경 추적을 할 수 있고 일급 컬렉션이 의도하는 상태와 행위를 한곳에 묶일 수 있지 않을까 생각합니다ㅎㅎ 

두분이 이야기 해준 덕분에 좋은 인사이트 얻어가네요~ 두분 의견 궁금합니다!

```java
@Entity
public class Question extends AbstractEntity {

	@Column
	private String title;

	@Lob
	private String contents;

	@Embedded
	private Answers answers = new Answers();

	private boolean deleted;

 	public void addAnswer(Answer answer) {
		answer.setQuestion(this);
		answers.add(answer);
	}
}

@Embeddable
public class Answers {

	@OneToMany(mappedBy = "question")
	private List<Answer> answers = new ArrayList<>();

	public void add(Answer answer) {
		answers.add(answer);
	}

	public void add(Answer answer) {
		answers.add(answer);
	}
}
```

**Comment by zbqmgldjfh** [comment]
저도 가장 먼저 생각한 방식은 흔하게 사용한 OneToMany 를 활용한 일급컬랙션 이였는는데 그럼에도 ElementCollection 방식을 선택해본 이유는 지금 다 간접 참조를 사용하는 DDD방식에서 어그리게이트 루트를 통해서만 사진에 접근하기 위해서 입니다.
ElementCollection이 테이블을 따로 만들기는 하지만 부모에 아예 종속시키는 방식이기 때문에 부모와 라이프 사이클을 함께 가니... 어그리게이트 루트를 통해 관리하기 편하겠구나 싶었는데,

근대 다시 생각해보니 이전 저의 생각이 틀린것 같습니다, 어짜피 oneToMany를 통해서도 자식을 보호할수 있으며, orphanRemove 적용하면 부모를 통해서 자식을 관리할수 있는것은 동일하네요! 

결론 : oneToMany를 통한 일급컬렉션을 사용하면 될것 같습니다!!

**Comment by zbqmgldjfh** [comment]
이 안건은 oneToMany를 활용한 일급컬랙션을 사용하기로 결정되었습니다!
