### ISSUE TITLE
[Setting] Security REST 기본 설정

### ISSUE THREAD

**Issue by vcho1958** [soolsul/soolsul-server#2]
## 🙋🏻‍♂️ 환경 세팅
폼 로그인 제거
Authorization 인증 제거
MVC패턴이 아닌 REST기 때문에 stateless로 설정
CSRF 설정 전이므로 disable
CORS 설정

## 📖 참고 사항
공유할 내용, 레퍼런스, 추가로 발생할 것으로 예상되는 이슈, 스크린샷 등을 넣어 주세요.
- 추가적으로 필요한 내용은 comment로 남겨주세요.

**Comment by zbqmgldjfh** [comment]
## 예시 코드
```java
    @Override
    protected void configure(HttpSecurity http) throws Exception {
        http
            .httpBasic().disable() // rest api 이므로 기본설정 사용안함. 기본설정은 비인증시 로그인폼 화면으로 리다이렉트 된다.
            .csrf().disable() // rest api이므로 csrf 보안이 필요없으므로 disable처리.
            .sessionManagement().sessionCreationPolicy(SessionCreationPolicy.STATELESS) // jwt token으로 인증하므로 세션은 필요없으므로 생성안함.
            .and()
                .authorizeRequests() // 다음 리퀘스트에 대한 사용권한 체크
                    .antMatchers("/signin", "/signup").permitAll() // 가입 및 인증 주소는 누구나 접근가능
                    // .antMatchers(HttpMethod.GET, "helloworld/**").permitAll() // hellowworld로 시작하는 GET요청 리소스는 누구나 접근가능
                    .anyRequest().hasRole("USER") // 그외 나머지 요청은 모두 인증된 회원만 접근 가능
            .and()
                .addFilterBefore(new JwtAuthenticationFilter(jwtTokenProvider), UsernamePasswordAuthenticationFilter.class); // jwt token 필터를 id/password 인증 필터 전에 넣는다
    }
```

JwtAuthenticationFilter 라는 사용자 정의 필터를 구현해주어야 함

**Comment by sween2591** [comment]
엔티티 먼저 만들고 해야합니당.
폼로그인 disable은
form().disable()
이에요
csrf는 rest API여도 추후 설정해야합니다.
스프링 시큐리티에서 지원하는 ROLE은 뒤에 _ROLE을 추가로 붙여주어야합니다.

**Comment by sween2591** [comment]
수정해야할 부분이 있네요. 스프링 부트 2.7부터는 WebSecurityConfigurerAdapter가 deprecated되어 extends하지 못합니다. 따라서 오버라이드가 아니라 Bean으로 선언해야하므로 작성하고 말씀드릴게요.
JwtFilter도 빈으로 만들어서 프로바이더를 자동으로 주입받아 생성하는 게 더 깔끔하지 않을까요?

**Comment by zbqmgldjfh** [comment]
아 저는 이거 그냥 "https://sybarits.github.io/2020/11/08/rest-api-security.html" 글 보면서 대충 어떤 느낌인지 `예시 코드`란 이름하에 올려둔겁 니다. ㅎㅎ
<img width="879" alt="image" src="https://user-images.githubusercontent.com/60593969/198539161-e3239421-633e-4f47-9d9d-62a38bde5b26.png">

위 코드 사용하겠다는 거 아닙니다!!

시큐리티는 테디가 더 잘할태니 편하신대로 하시면 될듯 합니다!!

**Comment by zbqmgldjfh** [comment]
몇가지 최근 공부한 내용 기반으로 말씀 드리자면,

우선 `hasRole("USER")` 의 경우 앞에 ROLE_ 은 필수조건이 아닙니다. ROLE_을 추가해야 하는 api는` hasAuthority` 입니다.
(https://stackoverflow.com/questions/19525380/difference-between-role-and-grantedauthority-in-spring-security)

그리고 WebSecurityConfigurerAdapter 같은 경우 deprecated 된거는 맞는데, 아직 상속하여 사용가능합니다!
최신 스펙을 따라가느냐, 예전 방식으로 가느냐의 차이인것 같습니다!!
(저같은 경우 현 학습중인 상황에서 WebSecurityConfigurerAdapter을 상속받아 구현중인데, 정상작동 하기는 합니다)

csrf는 rest API여도 추후 설정해야합니다.
-> 옙 최근에 학습해서, 알고 있습니다. (https://www.baeldung.com/csrf-stateless-rest-api)

**Comment by zbqmgldjfh** [comment]
JwtFilter도 빈으로 만들어서 프로바이더를 자동으로 주입받아 생성하는 게 더 깔끔하지 않을까요?
=> 테디가 맞습니다!! FIlter랑 프로바이더, successHandler, FailureHandler, DeniedHandler 다 빈으로 생성하게 만들어야 하며, LoginAuthenticationEntryPoint 정도는 그냥 등록할때 new 로 전달하면 될것 같습니다.
