### ISSUE TITLE
[Suggest] 코드 리뷰내용 피드백 시간 설정

### ISSUE THREAD

**Issue by pbg0205** [soolsul/soolsul-server#24]
## 🙋🏻‍♂️ 제안 사항
- 기능 개발 속도 향상과 빠른 피드백을 통한 코드 퀄리티를 증진시키기 위해 PR 이후 48 시간 이내에 리뷰를 하면 좋을 것 같습니다!

## 📖 참고 사항
공유할 내용, 레퍼런스, 추가로 발생할 것으로 예상되는 이슈, 스크린샷 등을 넣어 주세요.
- 추가적으로 필요한 내용은 comment로 남겨주세요.

**Comment by zbqmgldjfh** [comment]
24시간도 좋을것 같습니다?? 구현이 아닌 리뷰는 24시간안에 가능할것 같습니다!!! 중간마감이 다음주라 ㅠ,ㅠ

**Comment by pbg0205** [comment]
24시간 좋습니다!
