### ISSUE TITLE
[Bug] BaseEntity에 있는 ID 필드로 인한 Equals&HashCode 문제

### ISSUE THREAD

**Issue by zbqmgldjfh** [soolsul/soolsul-server#26]
## ❌ 버그 발생
현재 우리의 엔티티 들은 공통적으로 ID값을 BaseEntity 통해서 할당받고 있습니다.

따라서 Equal Hashcode를 구현할때 다음과 같이 자식에서는 UUID를 지정하여 식별할수가 없었습니다.
<img width="482" alt="image" src="https://user-images.githubusercontent.com/60593969/200747709-1fa9444a-e5c8-4d61-8cc1-16b5cf20fb28.png">

이게 문제가 된 지점이 다음과 같은 테스트 도중 이였습니다.
``` Java
    @Transactional
    @Rollback(value = false)
    @Test
    public void delete_test() {
        // given
        Post post = new Post("ownerId", "restaurantId", 4.2f, "contents");
        PostPhoto newPhoto1 = new PostPhoto(RESTAURANT_ID, "file1", "uuid1", ".jpg");
        PostPhoto newPhoto2 = new PostPhoto(RESTAURANT_ID, "file2", "uuid2", ".jpg");
        PostPhoto newPhoto3 = new PostPhoto(RESTAURANT_ID, "file3", "uuid3", ".jpg");
        post.addPhotoList(List.of(newPhoto1, newPhoto2, newPhoto3));

        postRepository.save(post);

        em.flush();
        em.clear();

        // when
        Post findPost = postRepository.findById(post.getId()).get();
        findPost.deletePhoto(newPhoto1);

        // then
        assertThat(findPost.getPhotos()).extracting("uuidFileUrl").contains("uuid2", "uuid3");
        assertThat(findPost.getPhotos().size()).isEqualTo(2);
    }
```
언뜻 보면 그냥 통과해야 할 테스트가 통과하지 않게 됬었습니다.
이는 Equal Hashcode를 를 통해 동일 엔티티로 식별하지 못해서 삭제하지 못했기 때문입니다...
<img width="329" alt="image" src="https://user-images.githubusercontent.com/60593969/200747974-de7e3d28-2c80-4873-b7ff-9a2681e18df8.png">

Equal Hashcode를 전체 필드로 했지만, 왜 PostPhoto사 서로간에 식별되지 않은것인지 이해할 수 없었습니다.

다만 해결책으로 UUID를 생성하고 있던 BaseEntity에 Equal Hashcode를 만들어 주니 성공적으로 서로간에 식별이 가능하게 되었고 테스트에 통과하였습니다.
``` Java
public abstract class BaseEntity {
    @Id
    @GeneratedValue(generator = "uuid")
    @GenericGenerator(name = "uuid", strategy = "uuid")
    private String id;

    protected BaseEntity(String id) {
        this.id = id;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        BaseEntity that = (BaseEntity) o;
        return Objects.equals(getId(), that.getId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId());
    }
}
```
## 🐞 발생한 위치
버그가 발생한 위치를 알려주세요.(Component, Page 등)

## 📖 참고 사항
공유할 내용, 레퍼런스, 추가로 발생할 것으로 예상되는 이슈, 스크린샷 등을 넣어 주세요.
- 추가적으로 필요한 내용은 comment로 남겨주세요.

**Comment by zbqmgldjfh** [comment]
일단은 BaseEntity 자체에 Equals HashCode를 구현해두었습니다!

**Comment by pbg0205** [comment]
해당 BaseEntity 는 작업 담당자가 해당 도메인으로 내리는 작업하도록 합시다!

**Comment by zbqmgldjfh** [comment]
넵!!
