### ISSUE TITLE
[Suggest] 술집 네이밍 제안

### ISSUE THREAD

**Issue by pbg0205** [soolsul/soolsul-server#28]
## 🙋🏻‍♂️ 제안 사항
저희 술집 네이밍이 `Restaurant` 로 되어있는데 도메인 특성상 `Bar` 가 어떨까하는 생각이 들어서 의견 제시합니다!

## 📖 참고 사항
공유할 내용, 레퍼런스, 추가로 발생할 것으로 예상되는 이슈, 스크린샷 등을 넣어 주세요.
- 추가적으로 필요한 내용은 comment로 남겨주세요.

**Comment by zbqmgldjfh** [comment]
냅 좋아요 빠르게 수정해보겠습니다!
