### ISSUE TITLE
[Setting] Nginx HTTPS 설정

### ISSUE THREAD

**Issue by vcho1958** [soolsul/soolsul-server#4]
## 🙋🏻‍♂️ 환경 세팅
로컬 서버에 앱서버를 배포합니다.
Route53, Let's Encrypt, Nginx 활용

## 📖 참고 사항
1. Route53에서 도메인 구매
2. 로컬 서버 고정 IP설정 및 공유기 포트포워딩
3. 80, 443 방화벽 해제
4. nginx 설치
5. lets encrypt 설치
6. lets encrypt에 도메인 검증
7. 인증 후 자동 생성 nginx 설정을 static 라우팅에서 앱서버로 요청을 전달하도록 proxy_pass 설정

**Comment by sween2591** [comment]
<img width="550" alt="image" src="https://user-images.githubusercontent.com/61648828/197649591-99f8b515-e943-4752-8ffd-c8b7ad1bfa0b.png">
1. 서버의 IP를 확인한다.
<img width="1167" alt="image" src="https://user-images.githubusercontent.com/61648828/197649658-f3a2e8ce-c4fd-4bd6-a9cb-e936555de552.png">
2. Route53에서 구매한 도메인을 A유형으로 해당 IP를 등록하여 AWS DNS를 통해 호스팅한다.

```
server{
  server_name soolsul.link
  location /{
    proxy_pass http://localhost:8082
  }
}
```
3. 위 사항을 nginx 환경설정 파일에 추가하여 HTTP(80)으로 오는 요청을 앱서버 포트로 전달한다.

**Comment by sween2591** [comment]
4. [lets encrypt 포스팅](https://happist.com/573990/%EC%B5%9C%EC%8B%A0-lets-encrypt-ssl-%EC%9D%B8%EC%A6%9D%EC%84%9C-%EB%B0%9C%EA%B8%89-%EB%B0%A9%EB%B2%95-3%EA%B0%80%EC%A7%80-%EC%A0%95%EB%A6%AC)을 참고하여 인증서를 발급받는다.
5. 
<img width="828" alt="스크린샷 2022-10-25 오전 8 39 27" src="https://user-images.githubusercontent.com/61648828/197650065-68fb1aac-4256-4a58-bad8-8994e3b5dfd7.png">
해당 블록에서 static 파일을 조회하는 root, index, try_files를 지우고
3번에서 했던 것처럼 proxy pass로 앱서버 포트에 포워딩해준다.
<img width="411" alt="스크린샷 2022-10-25 오전 8 40 54" src="https://user-images.githubusercontent.com/61648828/197650191-201564ee-6dbe-4cc5-a428-4e1edc116cc3.png">
6. 일반 요청은 위 블록에서 https로 리다이렉트시키며 https로 온 요청은 5번에서 letsencrypt로 생성된 ssl인증서를 통해 암호화를 해제한 후 내용을 앱서버로 포워딩해준다.
