### ISSUE TITLE
[Bug] Bar목록 조회시 문제 발생 부분

### ISSUE THREAD

**Issue by zbqmgldjfh** [soolsul/soolsul-server#49]
## ❌ 버그 발생
BarQueryRepository#findBarFilteredByConditions 사용시 문제 발생

생성자 부분에서 문제가 발생하는데 왜 이런것 일까요 ㅠ,ㅠ

## 🐞 발생한 위치
<img width="913" alt="스크린샷 2022-11-16 오후 4 42 57" src="https://user-images.githubusercontent.com/60593969/202118256-cc19b526-c0f0-43df-bb3b-5ed4ea8f987a.png">

## 📖 참고 사항
공유할 내용, 레퍼런스, 추가로 발생할 것으로 예상되는 이슈, 스크린샷 등을 넣어 주세요.
- 추가적으로 필요한 내용은 comment로 남겨주세요.

**Comment by pbg0205** [comment]
createAt 필드 추가해서 해결했슴다! 해당 브랜치에 푸쉬했어요~
