### ISSUE TITLE
[Design] ERD 설계

### ISSUE THREAD

**Issue by sween2591** [soolsul/soolsul-server#5]
## 💼 설계 내용
[다이어그램](https://dbdiagram.io/d/6356e40bfa2755667d61f0bd)

기본 요구사항을 충족하는 ERD를 설계하고
인증, 추가 기능을 고려한 엔티티를 추가합니다.

## 📖 참고 사항
[사용방법](https://www.dbml.org/home/)

**Comment by sween2591** [comment]
# 기본 요구사항 ERD
<img width="1845" alt="image" src="https://user-images.githubusercontent.com/61648828/197641726-baac0dbc-c087-4456-8ee0-bfd32d56d8f5.png">

```dbml
enum role{
  ADMIN_ROLE
  USER_ROLE
  GUEST_ROLE
}

Table user{//Security Authentication을 위한 프로퍼티 분리
  id bigint [pk]
  email varchar
  password varchar
  role role
  created_at timestamp
  updated_at timestamp
  indexes{
    (email) [unique] //중복
    created_at //개인정보 보호법 기간 체크
  }
}

Table refresh_token{
  id bigint [pk]
  user_id bigint [ref: - user.id]
  refresh_token varchar
  indexes{
    refresh_token
    (user_id, refresh_token) [unique]
  }
}

Table user_info{
  id bigint [pk]
  user_id bigint [ref: - user.id]
  region_id bigint [ref: > region.id] //같은지역 회원 조회
  phone varchar [unique] //중복체크
  name varchar 
  nickname varchar [unique] //중복체크
  indexes{
    region_id //지역별 검색
    user_id //로그인 시 사용자 정보 조회
  }
}

Table region{
  id bigint [pk]
  parent_id bigint [ref: > region.id] //상위 depth
  name varchar
  depth integer// 국가, 시/군/도, 동/면/읍
  lat decimal //위도
  lng decimal //경도
  indexes{
    parent_id //특정 카테고리의 하위 카테고리 조회시
    name //이름으로 조회 시
    depth
  }
}

Table post{//게시글(리뷰?)
  id bigint [pk]
  owner_id bigint [ref: > user_info.id]//작성자 검색
  region_id bigint [ref: > region.id] // 지역별 검색
  content varchar
  created_at timestamp
  updated_at timestamp
  indexes{
    created_at //시간순 정렬, 피드
    owner_id // 작성자 검색
    region_id // 지역별 검색
  }
}

enum attachment_type{
  PROFILE // 프로필 사진
  POST //게시글(리뷰?)
  MENU // 메뉴 사진
  REPLY // 댓글
  RESTAURANT // 식당
}

Table attachment{ //단일테이블 전략 상속으로 구현할 예정
  id bigint [pk]
  post_id bigint [ref: > post.id] //nullable
  reply_id bigint [ref: > reply.id] //nullable
  user_info_id bigint [ref: - user_info.id]//nullable
  unique_file_name varchar
  ext varchar
  original_file_name varchar
  dtype attachment_type
}

enum post_like_content{
  LIKE //따봉
  HELPED //도움이 됐어요
  FUN //재미있어요
  DISLIKE // 싫어요
}

Table post_like{//게시글(리뷰?) 좋아요
  id bigint [pk]
  owner_id bigint [ref: > user_info.id]
  post_id bigint [ref: > post.id]
  post_like_content post_like_content//페이스 북처럼 좋아요 종류 선택
  indexes{
    post_id
    owner_id
    (post_id, post_like_content, owner_id) [unique]// 인당 반응별로 1개씩 가능
    (post_id, post_like_content) //개수 조회 시
  }
}

Table post_scrap{//게시글(리뷰?) 스크랩
  id bigint [pk]
  owner_id bigint [ref: > user_info.id]
  post_id bigint [ref: > post.id]
  created_at timestamp
  indexes{
    owner_id// 본인이 스크랩한 개시글
    post_id// 스크랩된 횟수
    (owner_id, post_id) [unique] // 게시글당 인당 1개씩
  }
}


Table post_view{//조회수
  id bigint [pk]
  viewer_id bigint [ref: > user_info.id]
  post_id bigint [ref: > post.id]
  indexes{
    (post_id, viewer_id)[unique] //인당 한번씩만 카운트
    post_id //게시글 조회수 조회
  }
}

enum reply_response_type{//댓글 반응 종류 추후 페북처럼 사용할 수 있므
  HELPED
  FUN
}

Table reply{//댓글
  id bigint [pk]
  owner_id bigint [ref: > user_info.id] //작성자
  post_id bigint [ref: > post.id] // 게시글
  respond_id bigint [ref: > reply.id] //대댓글일 때 어떤 댓글의 댓글인지
  //대댓글이 내가 적은 댓글에 검색돼야하므로 같은 테이블로 할당
  //누르면 해당 게시글로 가야하므로 불필요한 조인을 줄이기 위해 분리하지 않음
  content varchar
  created_at timestamp
  indexes{
    owner_id //작성자별 조회
    post_id //게시글별 조회
    respond_id // 댓글별 조회
  }
}

Table reply_response{ //댓글 반응, 좋아요 등
  id bigint [pk]
  owner_id bigint [ref: > user_info.id] 
  reply_response_type reply_response_type
  reply_id bigint [ref: > reply.id]
  created_at timestamp
  indexes{
    owner_id 
    reply_id // 댓글 별 조회 
    (reply_id, reply_response_type)// 댓글별 반응별 개수 조회 혹은 사용자 조회
    created_at //시간순 정렬
    (reply_id, owner_id, reply_response_type) [unique] //인당 게시글당 반응당 1개씩
  }
}



// 여기까지 넘블 측 요구사항


```

**Comment by sween2591** [comment]
<img width="1731" alt="image" src="https://user-images.githubusercontent.com/61648828/197647537-721ce3ae-e765-498d-a6e4-5fe6bdcde78a.png">

```
Table post{//게시글(리뷰?)
  id bigint [pk]
  owner_id bigint [ref: > user_info.id]//작성자 검색
  restaurant_id bigint [ref: > restaurant.id] // 지역별 검색
  content varchar
  score decimal //리뷰라면 평점
  created_at timestamp
  updated_at timestamp
  
  indexes{
    created_at //시간순 정렬, 피드
    owner_id // 작성자 검색
    restaurant_id 
    //지역별 리뷰조회 구현
    // 지역을 기반으로 식당을 모두 검색한다. 
    //해당 id배열에 in연산으로 post의 restaurant_id를 검색한다.
  }
}

enum attachment_type{
  PROFILE // 프로필 사진
  POST //게시글(리뷰?)
  MENU // 메뉴 사진
  REPLY // 댓글
  RESTAURANT // 식당 메인사진
}

Table attachment{ //단일테이블 전략 상속으로 구현할 예정
  //연관관계는 지우거나 업로드 시 인가로직을 구성하기 위해서
  id bigint [pk]
  post_id bigint [ref: > post.id] //nullable
  reply_id bigint [ref: > reply.id] //nullable
  user_info_id bigint [ref: - user_info.id]//nullable
  restaurant_id bigint [ref: > restaurant.id]//nullable
  restaurant_menu_id bigint [ref: > restaurant_menu.id]//nullable
  uuid_file_url varchar
  ext varchar
  original_file_name varchar
  dtype attachment_type
  indexes{
    dtype
    ext
    restaurant_menu_id
    restaurant_id
    user_info_id
    reply_id
    post_id
  }
}


Table restaurant{
  id bigint[pk]
  region_id bigint [ref: > region.id]
  restaurant_category bigint [ref: > restaurant_category.id]
  lat decimal//위도
  lng decimal //경도
  indexes{
    (lat, lng)
    restaurant_category
    region_id
  }
}

Table restaurant_bookmark{
  id bigint [pk]
  user_info_id varchar [ref: > user_info.id]
  restaurant_id bigint [ref: > restaurant.id]
  created_at timestamp
  indexes{
    user_info_id
    restaurant_id // 점포별 북마크(찜) 개수
    created_at
  }
}

Table restaurant_open_time{
  id bigint [pk]
  restaurant_id bigint [ref: > restaurant.id]
  start_time timestamp
  end_time timestamp
  indexes{
    restaurant_id
    (start_time, end_time) // 지금 시간기준 오픈 여부
  }
}

Table restaurant_category{
  id bigint [pk]
  name varchar
  parent_id bigint [ref: > restaurant_category.id]
  depth integer //술집, 음식점 / 바, 감성주점 / 나이대
  indexes{
    parent_id
    depth
  }
}

Table menu_category{
  id bigint [pk]
  name varchar
  parent_id bigint [ref: > menu_category.id]
  depth integer //주류, 안주 / 한식 중식 양식/ 돈까스 / 치즈돈까스, 고구마돈까스
                            // 소주 맥주 양주 막걸리/ 참이슬
  indexes{
    depth
    parent_id
  }
}

Table restaurant_menu{ 
  id bigint [pk]
  restaurant_id bigint [ref: > restaurant.id]
  menu_category bigint [ref: > menu_category.id]//주류, 메뉴 종류 검색을 통해 가게 확인 가능
  cost bigint
  created_at date
  indexes{
    restaurant_id
    menu_category // 메뉴 카테고리별로 검색후 restaurant_id 중복제거하여 
    //해당 카테고리 메뉴를 파는 가게 검색 가능
    (restaurant_id, menu_category) //가게 카테고리별 메뉴 검색
  }
}

```

**Comment by zbqmgldjfh** [comment]
## 💼 설계 내용
![술술 ver2](https://user-images.githubusercontent.com/60593969/197691625-4b02f47f-6496-4403-bbfd-19472b8a74b9.png)

기본 틀은 테디가 만들어준 부분 사용 그대로 사용하려 노력하였습니다. (테디의 노고에 감사를!!)
몇가지를 수요일날 함께 고민하면 좋을것 같습니다!!

### 1. Refresh 토큰을 RDB로 관리 해야 할까요? 고민고민~~

### 2. user 와 user_info
“둘을 분리시키는 것이 더 효율적인가?” 에 대한 고민

### 3. 하나로 되어있던 attach
테디가 의도하는바를 알겠습니다!, 다만 상속을 통해 하나로 관리하는 것은 양날의 검인 부분이 있다 생각하여
수요일날 한번더 의논합시다!!!

## 코드
```sql
Table restaurant{
  id long[pk]
  name varchar
  phone varchar
  restaurant_category long [ref: > restaurant_category.id]
  latitude decimal //위도
  longitude decimal //경도
  
  city varchar
  gu varchar
  road varchar
}

Table restaurant_images{
  id long[pk]
  restaurant_id long [ref: > restaurant.id]
  image varchar
}

Table restaurant_category{
  id long [pk]
  name varchar
  parent_id long [ref: > restaurant_category.id]
  depth integer
}

Table restaurant_menu{ 
  id long [pk]
  restaurant_id long [ref: > restaurant.id]
  menu_category long [ref: > menu_category.id]
  cost bigint
  created_at date
}

Table menu_category{
  id long [pk]
  name varchar
  parent_id long [ref: > menu_category.id]
  depth integer
}

Table restaurant_operating_time{
  id long [pk]
  restaurant_id long [ref: > restaurant.id]
  start_time timestamp
  end_time timestamp
}

Table user{
  id long [pk]
  email varchar
  password varchar
  role role
  created_at timestamp
  updated_at timestamp
  deleted boolean
}

Table user_info{
  id long [pk]
  user_id long [ref: - user.id]
  phone varchar [unique] 
  name varchar 
  nickname varchar [unique]
  avatar varchar
}

Table post{
  id long [pk]
  user_id long [ref: > user.id]
  content varchar
  view_count bigint
  created_at timestamp
  updated_at timestamp
  deleted boolean
}

Table reply{
  id long [pk]
  user_id long [ref: > user.id] //작성자
  post_id long [ref: > post.id] // 게시글
  respond_id long [ref: > reply.id] 
  content varchar
  created_at timestamp
}

Table attach_reply{ //댓글 반응, 좋아요 등
  id long [pk]
  reply_id long [ref: > reply.id]
  user_id long [ref: > user.id] 
  reply_response_type reply_response_type
  created_at timestamp
}

Table restaurant_post{
  id long [pk]
  reply_id long [ref: > reply.id]
  post_id long [not null, ref: > post.id]
  restaurant_id long [not null, ref: > restaurant.id]
  uuid_file_url varchar
  original_file_name varchar
}

Table restaurant_bookmark{
  id long [pk]
  user_id long [ref: > user.id]
  restaurant_id long [ref: > restaurant.id]
  created_at timestamp
}

Table post_scrap{//게시글 스크랩
  id long [pk]
  post_id long [ref: > post.id]
  user_id long [ref: > user.id]
  created_at timestamp
}

enum post_like_type{
  LIKE // 좋다
  DISLIKE // 싫어요
  // 종류는 고민 
}

Table post_like{ // 좋아요 종류
  id long [pk]
  post_id long [ref: > post.id]
  user_id long [ref: > user.id]
  post_like_content post_like_type//좋아요 종류 선택
}

Table alcohol{
  id long [pk]
  name varchar [not null]
  price bigint [not null]
  category_id long [ref: > menu_category.id]
}

Table snack{
  id long [pk]
  name varchar [not null]
  price bigint [not null]
  category_id long [ref: > menu_category.id]
}
```


## 📖 ERD 링크
https://dbdiagram.io/d/63573544fa2755667d64701f

**Comment by sween2591** [comment]
리프레쉬 토큰은 안에 자료가 있으면 안되고 계정당 하나만 발급돼야합니다따라서 유효성을 검사한 후 디비에서 매칭시켜 얻은 사용자정보를 가지고 엑세스와함께 재발급 받는 과정을 거쳐야합니다.
https://velog.io/@breeze202/%EC%9D%B4%EA%B2%83%EB%A7%8C%EC%9D%80-%EC%95%8C%EA%B3%A0%EA%B0%80%EC%9E%90-%ED%86%A0%ED%81%B0%ED%86%A0%ED%81%B0
대부분의 구현은 RDB에 저장을 하나 레디스나 캐시에 저장할 수도 있긴합니다.
근데 캐시에 저장하게되면 서버가 중단되거나 할 때 사용자들이 전부 재로그인을 해야하는 상황이 생길수도 있어요.
레디스를 넣을 생각이 있다면 RDB에 저장안하는 건 찬성입니다!!

**Comment by sween2591** [comment]
Attach reply의 경우 제가 작성한 댓글에 함께 검색이 가능해야합니다. 또한 클릭 시 게시글로 이동해야하는데
이를 분리하게되면 잦은 join이 발생할 것 이라고 생각하는데 이 점은 어떻게 생각하시나요?

**Comment by sween2591** [comment]
city gu road를 문자열로 저장하는 이유가 있나요?
region으로 굳이 카테고리처럼 분리한 이유는 검색을 할 때 외래키로만 검색할 수 있다는 장점이 있기때문입니당.

**Comment by sween2591** [comment]
파일은 별도의 테이블로 설계하는 것이 좋다고 알고 있습니다.
또한 1개만 올릴것도 아니기 때문에 분리를 시켰는데 필드로 할당하신 이유가 있을까요?

테이블에는 딱 연관있는 정보만 있는 게 맞다고 생각해요. 좌표 등의 정보를 가지고 있게되면 불필요한 부분이 수정될 때 나머지 컬럼까지 팬텀리드 현상이 일어나 예기치 않은 오류가 발생할 수 있다고 생각합니다.

또한 프로필이미지를 avatar라고 하신 이유가 있을까요? 서비스 로직을 짤 때 의미를 이해하기 힘들 것 같습니다.

**Comment by sween2591** [comment]
회의시간까지 시간이 지연되는 것도 좋지 않은 것 같아요. 
코멘트를 포함해서
각 변경의 이유를 주석으로 달아주셨으면 좋겠어요!
구체적으로 어떤 장점이 있어서 변경하게 되신건지 알고 싶습니다.

**Comment by sween2591** [comment]
메뉴를 분리 하는 건 찬성입니다. 근데 저희가 추후 일반 음식점도 확장을한다면 snack보다 범용적으로 그냥 menu라고 하는 게 좋지않을까요?

**Comment by sween2591** [comment]
상속은 양날의 검일 수 있지만 애플리케이션 단에서 로직을 처리할 때 JPA가 제공해주는 기능을 더 잘 사용할 수 있다고 생각합니다.
굳이 조인테이블이 아닌 싱글테이블 전략으로 한 이유는 김영한님 강의에서 싱글테이블 전략을 사용하면 조인이 적어지고 레포지터리 상의 코드가 깔끔해진다는 의견을 말해주셨기 때문입니다. 본인도 DBA분과 매번 그걸로 토의하는 경우가 많다고 하실정도로
널이 많아져 저장공간상에선 비효율적이지만 그만큼 코드로 볼 수 있는 장점이 많다고 생각합니다.
애초에 객체로 매핑하는 것 자체가 애플리케이션 로직상의 이점을 챙기기 위해 정확히 디비설계와 매칭되지 않는 부분을 포기한 것이라고 생각합니다.

**Comment by zbqmgldjfh** [comment]
넵 사실 RDB가 아니라, Redis로 관리하자는 의미입니다.
예전에 RDB로 관리할려 해본적이 있는데, 스케쥴러를 따로 만들어 일정 주기마다 쿼리를 날려 만료시간을 확인해야한다는 점이 불편했었습니다.
Reids의 expire를 통해 자도만료 시킬 생각이였습니다!!

**Comment by zbqmgldjfh** [comment]
Attach reply 이거 원래 테디가 만들어 주셨던 attach에서 이름만 Attach reply로 변경한것 입니다!!
기존의 (post - attach - reply) 관계에서 (post - attach_reply - reply) 로 3개의 스키마 간에 관계는 동일합니다.

**Comment by zbqmgldjfh** [comment]
기존에 region을 사용할 경우 “서울시, 구로동, xx로”일 경우  이걸 공유해주신 Entity Tree구조로 만드신다는 의미 인가요?? 
사실 이부분이 명확하지 않아 따로 생각하긴 했습니다만....

또한 주소 정보는 `restaurant` 에만 있으면 된다 생각했어서 따로 분리하지 않았습니다.
추가로 (시, 동, 로)3개의 key를 묶어 인덱스를 적용하면 search 성능이 향상됩니다!

그 'gu' 이런 이름 자체는 변경하긴 해야 합니다.

**Comment by zbqmgldjfh** [comment]
그 파일이 avatar 말씀하시는 것 맞죠! avatar 딱 하나만 유저 인포에 있으면 된다 생각했습니다.
나머지 restaurant 같은 경우 따로 말씀하신것 처럼 별도 테이블로(restaurant_images) 분리되어 있습니다.

또한 좌표정보는 restaurant 에 있는게 알맞지 않나요?? 해당 엔티티 내부에 회의에서 말했듯 VO로 만들 생각이였습니다.

팬텀 리드 언급하셨는데, mysql 상에서는 레코드 락과 갭 락을 합친 넥스트 키 락을 사용하기때문에 팬텀리드는 발생하지 않는것으로 알고 있습니다.

마지막으로 avatar가 의미가 명확하지 않다는 점 조금은 주관적인것 같습니다. 
사실 avatar로 예전부터 프로필 이름을 사용했는데, 이는 github에서 OAuth 서버에서 넘겨주는 프로필에 avatar로 사용중이길래 좀더 대중적인 이름이다? 싶어 사용중입니다.

**Comment by zbqmgldjfh** [comment]
"회의시간까지 시간이 지연되는 것도 좋지 않은 것 같아요."
음 이게 저희 둘이 팀이면 바로 추가할탠데, 팀원이 한명 더 있는 상황에서 같이 의견 공유 못하는 부분은 좋지 못한다고 생각합니다.
뭘해도 다같이 함께 의논하는것이 더 좋을것 같습니다!

**Comment by zbqmgldjfh** [comment]
menu, 아 이건 별 뜻 없습니다 ㅎㅎ 술안주라는 의미를 좀 강조하고 싶었을 뿐입니다 ㅎㅎ menu 좋은것 같아요!

**Comment by zbqmgldjfh** [comment]
저도 강의를 들었기 때문에 해당 주석 봤을때 이부분을 동일하게 생각했었습니다. 
테디 의견이 맞는말이라, 그냥 장단점을 한번 같이 생각해봤으면 좋겠다는 의미였습니다! 
그리고 사실 스키마 하나에 nullable 한 부분이 있으면, 이를 상속한 child마다 속성을 지정할때 주의해서 사용해야 한다 생각했습니다.
테디가 위에서 말해주신 "불필요한 부분이 수정될 때 나머지 컬럼까지 수정하여 예기치 않은 오류가 발생할 수 있다고 생각합니다." 부분이 이부분에서 걱정되긴 했습니다.

**Comment by sween2591** [comment]
아 attachment는 첨부파일이었는데요! 대댓글과 다른 겁니다.

**Comment by sween2591** [comment]
존에 region을 사용할 경우 “서울시, 구로동, xx로”일 경우 이걸 공유해주신 Entity Tree구조로 만드신다는 의미 인가요??
넵 이게 제 의도이고 동까지는 사용하되 다른 부분은 상세주소 컬럼을 이용하여 표기할 계획이었습니다.
외래키로 검색하면 되므로 인덱싱도 간략화할 수 있을 것 같았어요
region에 좌표가 있는 이유는 본인 지역에 거리가 돼야 해당 지역을 지정할 수 있게 한다는 조건이 있었기 때문입니다.

**Comment by pbg0205** [comment]
위에서 논의한 부분에 관한 제 생각을 피드백 드려요~

> 리프레쉬 토큰은 안에 자료가 있으면 안되고 계정당 하나만 발급돼야합니다따라서 유효성을 검사한 후 디비에서 매칭시켜 얻은 사용자정보를 가지고 엑세스와함께 재발급 받는 과정을 거쳐야합니다. https://velog.io/@breeze202/%EC%9D%B4%EA%B2%83%EB%A7%8C%EC%9D%80-%EC%95%8C%EA%B3%A0%EA%B0%80%EC%9E%90-%ED%86%A0%ED%81%B0%ED%86%A0%ED%81%B0 대부분의 구현은 RDB에 저장을 하나 레디스나 캐시에 저장할 수도 있긴합니다. 근데 캐시에 저장하게되면 서버가 중단되거나 할 때 사용자들이 전부 재로그인을 해야하는 상황이 생길수도 있어요. 레디스를 넣을 생각이 있다면 RDB에 저장안하는 건 찬성입니다!!

 저는 RDB에 refresh token을 저장하는 방법도 좋을 것 같아요~ 이전에 저희 모두 레디스에 관한 핸들링이 부족하다고 이야기했었고 개발 단계에서 RDB에서 레디스로 개선하는 과정은 단순 외래키만 필드로 추가하고 있어서 개선 작업에 대한 허들이 높지 않을 것 같아요. MVP를 완성하는 것이 우선 순위에 초점을 둬서 레디스는 TO-BE 리스트로 두는 방법이 좋을 것 같습니다!

**Comment by pbg0205** [comment]
<img width="227" alt="image" src="https://user-images.githubusercontent.com/48561660/197752471-ec158154-9185-4ad4-826f-b93459fc0b63.png">

@vcho1958 @zbqmgldjfh  저는 이 방법도 괜찮은 것 같아요! 어제 시군구를 추가하는 이유는 카카오맵에서 지원 해주지만 API 요청 및 응답을 받는 시간보다 컬럼을 추가해서 검색조건으로 사용하는 목적인 것으로 기억합니다 😄 ( + 특정 지역 술집을 공유하는 도메인 특성에서는 괜찮은 접근으로 생각했습니다!)
혹시 잘못 기억하고 있는 부분이 있다면 말씀 부탁드려요 🙏

**Comment by pbg0205** [comment]
<img width="617" alt="image" src="https://user-images.githubusercontent.com/48561660/197754102-e51c2cf9-ca04-47c8-af30-48f705530fb0.png">
<img width="1197" alt="image" src="https://user-images.githubusercontent.com/48561660/197755045-b9ca8d9b-8d76-40d4-9549-f6aec65b6220.png">

저는 여기서 안주와 술을 구분하는 방법으로 접근해봤어요~ 저희 도메인의 특성이 술집을 큐레이션, 공유하는 서비스이기 때문에 안주와 술은 구분해서 관리해서 좋을 것 같다는 생각을 했습니다! (아래 내용은 간단하게 엔티티 작업한 내용이라서 참고만 부탁드립니다~)

**Comment by sween2591** [comment]
@pbg0205 @zbqmgldjfh 
시 동 로 3가지 컬럼을 복합키로 하는 것도 좋은 방법이라고 생각하지만
카테고리처럼 검색할 때 불편함이 있을 것이라고 생각합니다.
region으로 구분했던 이유도 회원가입 때 user_info에 입려된 지역정보를 기반으로 동일한 외래키로 검색하기 위해서에요!
굳이 식당에서만 쓰인다면 상관없지만 당근마켓, 기타 지역기반 서비스들처럼 카테고리로 검색하기 위해서는 무리가 있다고 생각합니다.

**Comment by sween2591** [comment]
저도 강의를 들었기 때문에 해당 주석 봤을때 이부분을 동일하게 생각했었습니다.
테디 의견이 맞는말이라, 그냥 장단점을 한번 같이 생각해봤으면 좋겠다는 의미였습니다!
그리고 사실 스키마 하나에 nullable 한 부분이 있으면, 이를 상속한 child마다 속성을 지정할때 주의해서 사용해야 한다 생각했습니다.
테디가 위에서 말해주신 "불필요한 부분이 수정될 때 나머지 컬럼까지 수정하여 예기치 않은 오류가 발생할 수 있다고 생각합니다." 부분이 이부분에서 걱정되긴 했습니다.
해당 내용은 일리가 있지만 JPA 상속전략을 써서 상송하게되면 타입에 대한 부분은 클래스의 종류에 따라 자동으로 처리해줍니다.
서비스 로직 상에서는 상송된 다른 child의 컬럼에 접근할 수 없게 설계돼있어요. 물론 JPQL등으로 처리하면 가능하긴한데 그렇게 사용하려면 상속전략을 사용을 안하는 게 맞습니다.
검색할 때도 해당 클래스를 셀렉트하면 자동으로 Dtype적용해서 쿼리를 날려줘요.
"불필요한 부분이 수정될 때 나머지 컬럼까지 수정하여 예기치 않은 오류가 발생할 수 있다고 생각합니다. "
이건 서비스로직상에서 해당 컬럼에 접근할 수 있는 설계일 경우에 해당하는 걱정이었습니다.

**Comment by pbg0205** [comment]
https://dbdiagram.io/d/63606a015170fb6441d32afe

- @zbqmgldjfh 수고 많으셨습니다 샤인 👍 👍 
- 한가지 질문이 있어서 문의드려요~ Restaurant_category 테이블에서 parent_id 를 가지며 계층 구조를 이루고 있는데
   한식, 양식, 중식과 같이 카테고리로 선언한걸로 기억하고 있어서요ㅎㅎ 혹시나 parent_id 를 선언해주신 이유가 있을까 해서 질문드립니다!

**Comment by sween2591** [comment]
@pbg0205 아 그건 제 의도였는데
추후 확장 가능성을 고려했습니다.
RDB구조상 제약사항이 걸릴경우 추후 변경이 어렵잖아요?
데이터를 마이그레이션하는 코스트를 고려했을 때 초기부터 저렇게 하는 게 낫겠다 싶어서 그렇게 방치했습니다.
애초에 깊이를 1로 둬서 할 거라면 루트 노드라고 해서 parent_id없이 깊이 0으로 처리하면 되는 것 같구요!

**Comment by zbqmgldjfh** [comment]
## ERD ver3
https://dbdiagram.io/d/63606a015170fb6441d32afe
![술술 ver3](https://user-images.githubusercontent.com/60593969/199857838-f0269070-ecb2-42ff-a974-9119197b3c04.png)

**Comment by zbqmgldjfh** [comment]
@vcho1958 추후 확장을 처음부터 고려할 필요는 없다 생각합니다!
쿠퍼 말처럼 카테고리 테이블을 분리하였으니, 아직까지는 depth를 사용하면서 내려갈일이 없다 생각됩니다(?)
우선 제거하고 추후 필요시 추가하죠! 

ERD가 추후 수정하기 어렵다는 말에 동의하지만, 해당 기능이 필요한 시점이 오면 변경은 가능할것 같습니다!
