### ISSUE TITLE
[Suggest] PR 이전에 gradle build 성공 확인하기!

### ISSUE THREAD

**Issue by pbg0205** [soolsul/soolsul-server#52]
## 🙋🏻‍♂️ 제안 사항
서버 배포시 빌드 과정에서 테스트 코드가 실패할 경우 빌드 실패가 되는 부분을 미연에 방지하기 위해 빌드 성공임을 확인합시다!
만약 당장 해결할 수 없는 실패 테스트는 `@Disabled` 을 처리해 이후에 해결하도록 합니다!

## 📖 참고 사항
공유할 내용, 레퍼런스, 추가로 발생할 것으로 예상되는 이슈, 스크린샷 등을 넣어 주세요.
- 추가적으로 필요한 내용은 comment로 남겨주세요.

**Comment by zbqmgldjfh** [comment]
넵 확인하였습니다!!
