### ISSUE TITLE
[Share] Redis 도입

### ISSUE THREAD

**Issue by pbg0205** [soolsul/soolsul-server#55]
## 🙋🏻‍♂️ 공유 사항
지도 확대 레벨과 리프레시 토큰을 관리하는데 레디스를 도입하기로 했습니다!

## 📖 참고 사항
공유할 내용, 레퍼런스, 추가로 발생할 것으로 예상되는 이슈, 스크린샷 등을 넣어 주세요.
- 추가적으로 필요한 내용은 comment로 남겨주세요.

**Comment by zbqmgldjfh** [comment]
좋아요 추후 반영해봅시다!!
