### ISSUE TITLE
[Share] 지도 확대 레벨 설정

### ISSUE THREAD

**Issue by pbg0205** [soolsul/soolsul-server#56]
## 🙋🏻‍♂️ 공유 사항
- 지도 확대 레벨은 카카오 API 레벨 표시 단위 미터 기준 `x3` 을 반지름으로 설정하기로 하였습니다!

## 📖 참고 사항
공유할 내용, 레퍼런스, 추가로 발생할 것으로 예상되는 이슈, 스크린샷 등을 넣어 주세요.
- 추가적으로 필요한 내용은 comment로 남겨주세요.

**Comment by zbqmgldjfh** [comment]
우선은 RDB를 사용하여 level당 거리 가져오도록 구현

**Comment by pbg0205** [comment]
범위는 반경 x3으로 설정할 예정
