### ISSUE TITLE
[Suggest] 경위도 타입 변경

### ISSUE THREAD

**Issue by pbg0205** [soolsul/soolsul-server#63]
### 데이터 타입 `double -> BigDecimal` 변경

- 테스트 코드를 작성하는 과정에서 `부동소수점 방식`으로 인해 데이터 일관성이 깨지는 현상을 확인했습니다.
- 현재 우리 서비스에서는 경위도를 통해 술집을 제공하는 서비스인 특성상 위치의 정확성이 떨어지는 것은 서비스에 영향이 있을 수 있을 것 같습니다.
- 아래 발현 현상 스크린샷 공유합니다.
   (좌 : LocationRangeService | 우 : UserLocationBasedSquareRange)

![image](https://user-images.githubusercontent.com/48561660/202841938-c3765b18-90d9-4027-a987-c8675f7fae92.png)

## 📖 참고 사항
공유할 내용, 레퍼런스, 추가로 발생할 것으로 예상되는 이슈, 스크린샷 등을 넣어 주세요.
- 추가적으로 필요한 내용은 comment로 남겨주세요.

**Comment by zbqmgldjfh** [comment]
넵 우선 BigDecimal로 바꾸는게 무조건 찬성합니다!
근데 이게보통 소수점 끝자리 가 달리지기는 하는데... 이게 소수점 3번째 자리부터 달라지기는 힘들탠데....
어떤 테스트 인지 테스트 코드를 한번 보여주실수 있을까요??!!

**Comment by pbg0205** [comment]
![image](https://user-images.githubusercontent.com/48561660/202849638-8c70d79c-7237-4d0c-b3ed-61d23800cf37.png)

- 같은 로직을 넣고 테스트 해본 내용 입니다!

**Comment by pbg0205** [comment]
다시 확인해보니 레벨 값이 달라서 그런거네요 
같게 나옵니다 ~ 이슈 닫을게요!
