### ISSUE TITLE
[Suggest] 파일 끝 개행 추가하기!

### ISSUE THREAD

**Issue by zbqmgldjfh** [soolsul/soolsul-server#64]
## 🙋🏻‍♂️ 제안 사항
파일의 끝에는 항상 개행을 추가 해주는것이 좋다 배웠습니다 (Posix문서 명세상)
https://blog.coderifleman.com/2015/04/04/text-files-end-with-a-newline/

인텔리제이에서 설정하면 커밋할때 자동 적용되지 사용하면 좋을것 같습니다!!

## 📖 참고 사항
공유할 내용, 레퍼런스, 추가로 발생할 것으로 예상되는 이슈, 스크린샷 등을 넣어 주세요.
- 추가적으로 필요한 내용은 comment로 남겨주세요.

**Comment by pbg0205** [comment]
버전업 하면서 설정 누락됐네요~ 추가할게요
