### ISSUE TITLE
[Suggest] auto import 설정

### ISSUE THREAD

**Issue by pbg0205** [soolsul/soolsul-server#65]
## 🙋🏻‍♂️ 제안 사항

프로젝트 파일에 미사용 import 를 제거하는 설정 추가해놓으면 좋을 것 같아요!
- https://www.jetbrains.com/help/idea/creating-and-optimizing-imports.html

## 📖 참고 사항
공유할 내용, 레퍼런스, 추가로 발생할 것으로 예상되는 이슈, 스크린샷 등을 넣어 주세요.
- 추가적으로 필요한 내용은 comment로 남겨주세요.

**Comment by zbqmgldjfh** [comment]
꿀팁 하나 얻어갑니다~~
