### ISSUE TITLE
[Share] @equalsAndHashCode 사용 제거 제안

### ISSUE THREAD

**Issue by pbg0205** [soolsul/soolsul-server#76]
## 🙋🏻‍♂️ 공유 사항

```
Using @EqualsAndHashCode for JPA entities is not recommended. It can cause severe performance and memory consumption issues. 
(JPA 엔터티에 @EqualsAndHashCode를 사용하는 것은 권장되지 않습니다. 심각한 성능 및 메모리 소비 문제가 발생할 수 있습니다.)
```
- intellij 에서 제공하는 위와 같은 이유로 equals, hash 메서드는 롬복을 사용하지 않는 것이 좋겠습니다.

## 📖 참고 사항
공유할 내용, 레퍼런스, 추가로 발생할 것으로 예상되는 이슈, 스크린샷 등을 넣어 주세요.
- 추가적으로 필요한 내용은 comment로 남겨주세요.

**Comment by zbqmgldjfh** [comment]
오호 넵~!! 인텔리제이 기능을 통해 오버라이딩 정의 하도록 하겠습니다!
