### ISSUE TITLE
[Share] 문서 자동화에 관한 고민

### ISSUE THREAD

**Issue by pbg0205** [soolsul/soolsul-server#78]
## 🙋🏻‍♂️ 공유 사항
문서 자동화에 관해 고민해보면 좋을 것 같습니다. 프론트 측에서 API 요청 방식에 관한 문의가 많고 API 변경에 관한 내용을 구두로 전달하는데는 어려움이 있는 것 같습니다~~ 기존에 Rest Docs 를 사용하기로 했지만 실사용은 하고 있지 않아 이 부분도 조금 고민해볼 필요가 있을 것 같아요!

## 📖 참고 사항
공유할 내용, 레퍼런스, 추가로 발생할 것으로 예상되는 이슈, 스크린샷 등을 넣어 주세요.
- 추가적으로 필요한 내용은 comment로 남겨주세요.

**Comment by zbqmgldjfh** [comment]
아 맞습니다.. 이게 시간 압박이 없으면.. 원래 순서상..
![image](https://user-images.githubusercontent.com/60593969/203069453-c37671c1-c39e-419d-b6d1-a7c05275c4d9.png)
위와 같이 인수테스트 작성후 문서화가 들어가야 하는데.... 시간이 없어 작성하지 못하고 있는것 같습니다...

초반에라도 잠시 Swager를 사용하는것도 좋은것 같습니다!! (Swager를 사용해본적이 없긴 합니다... ㅎㅎ)
다만 향후에 꼭 제거 해야 한다 생각합니다. 부가적인 애노테이션이 너무 많아져서요!!
