### ISSUE TITLE
[Suggest] 브랜치 전략 제안

### ISSUE THREAD

**Issue by sween2591** [soolsul/soolsul-server#8]
## 🙋🏻‍♂️ 제안 사항
현재 진행처럼 한 PR에서 작업 시에 충돌이 발생할 확률이 높아집니다.
따라서 본인이 작업할 내역에따라 해당 브랜치에서 - 를통해 한번 더 태그를 달아 브랜치를 분리했으면 합니다.
ex) feat-#6-User
feat-#6-Restaurant

이후 PR을 날릴 땐 갈리치기했던 브랜치에 하면 됩니다.
feat-#6 <- feat-#6-User

또한 PR에 어째서 그렇게 설계했는지 이유와 엔티티 코드를 첨부할 수도 있으니 프로젝트 전반적으로 도움이 될 것입니다.
## 📖 참고 사항
공유할 내용, 레퍼런스, 추가로 발생할 것으로 예상되는 이슈, 스크린샷 등을 넣어 주세요.
- 추가적으로 필요한 내용은 comment로 남겨주세요.

**Comment by zbqmgldjfh** [comment]
좋은 의견입니다!

다만 한번에 다 구현해도 되는 상황이면, 불필요 하게 전부 브렌치를 나눠서 PR을 날릴 필요가 없다고 생각됩니다!

예를 들어 어떠한 이슈 #6 을 만든상황에서, 하나의 브렌치로 끝낼수 있으면 #6으로 작업을 끝내고 PR을 날리고,
만약 해당 #6을 여러 사람이 구현해야 하는 상황이라면 그때 #6-User, #6-Snack 와 같이 분리하면 될것 같습니다!

**Comment by gusckd57** [comment]
@zbqmgldjfh 아뇨 필요합니다. 팬텀 리드라고 아시나요? 비슷한 이유입니다.

**Comment by gusckd57** [comment]
그리고 사실 브랜치나 이슈를 그렇게 추상적이고 큰 단위로 잡는 것도 추후 작업사항을 추적할 때 좋지 않습니다.

**Comment by sween2591** [comment]
@zbqmgldjfh 아뇨 필요합니다. 팬텀 리드라고 아시나요? 비슷한 이유입니다.
저희 셋이 소켓통신처럼 실시간으로 주고받을 수 있는 상황이 아닌 이상 없는 사람이 있다면 작업할 요소를 폴링하듯이 주기적으로 최신화하는 게 맞습니다.
팀플할 때도 많이 겪었구요. 결국 이번에도 다 하지 못하고 제가 생성했듯이 이런 상황은 협업에서 마이너스가 된다고 생각합니다.
이번 엔티티 작업의 경우 카톡상이나 회의상에 정확하게 언제부터 시작한다는 명확한 언급조차 없었고 저는 깃헙앱 커밋알람이 없었으면 어떤 게 진행중인지 알아차릴 수 없는 상황이었습니다.
이런 상황에서 제가 작업도중 급하게 필요하여 멋대로 비어있는 템플릿에서 엔티티를 생성한다고하면 불필요한 작업을 한 것이 되며 큰 리소스 낭비입니다.
도메인이 나뉘어 있지도 않은 상태에서 다같이 하기로 했으면 다같이 진행상황이 공유되어야 하는 게 맞죠.

**Comment by sween2591** [comment]
그리고 사실 브랜치나 이슈를 그렇게 추상적이고 큰 단위로 두루뭉실하게 정의하는 것도 추후 작업사항을 추적할 때 좋지 않습니다.
최소 투두리스트처럼 구체적으로 진행사항을 다른 사람이 파악할 수 있을 만큼은 작성해주셔야해요.
주기적으로 코멘트를 달든 하거나요.

**Comment by zbqmgldjfh** [comment]
@vcho1958 
아 우선 말씀해주신것 처럼 작업후 말씀을 전달하지 못해 서로 충돌이 날수 있었던점 죄송합니다 ㅎㅎ
사실 브렌치에 이슈 번호 추가해 두었고, file change 보면 다 알수 있는 부분이라 이러한 부분을 생각하지 못했던것 같습니다.

다만, 화요일에 8시에 엔티티 작업을 한다고 분명 월요일 전체 회의때 결정하고 게더타운을 나갔습니다. 
심지어 프론트 분들도 알고 있던 사항이라 카톡에 보면 yuna가 닉에게 내일 백엔드 회의 있으니 같이 nick에게 설명하자 했습니다 ㅎㅎ

**Comment by sween2591** [comment]
회의 차원의 문제가 아니지 않나요? 만약 앞으로도 이렇게 지속할 생각이라면 좀 안 맞는 것 같습니다.
PR 작성이 되어있는 것도 아니고 팀원이 일일이 코드의 의도를 파악하는 것은 무리가 있다고 봅니다.
PR에 이슈 번호 추가한건 제가 한 사항인데..
회의를 참석하지 못한 건 죄송합니다. 
정말 죄송하지만 구체적인 이슈, 코멘트 작성이 힘들다면 제가 생성한 이슈나 회의 때 같이 세부사항 작성하고 그 사항에 대해서만 작업을 진행해주세요.

**Comment by zbqmgldjfh** [comment]
우선 저도 죄송하다는 말 다시 한번 전하고 싶습니다. 이게 빨리 엔티티 까지는 만들어 놔야 분업이 될것 같아 전날 ERD가 다 완성 됬다고 들어서 진행하게 되었습니다. 사실 화요일에 모이자 했던 이유가 엔티티 까지는 만들자는 의도이기도 했구요...
그렇게 작업하던 도중 해당 ERD에 대하여 모르는 부분이(직전 회의에서 결정한 부분들이 반영안되 있었거든요) 있었습니다...
따라서 중간에 멈추게 된것 같습니다.
그리고 완성되지 않아 당연히 PR은 날려두지 않았엇습니다, 다음날 ERD가 다 수정되면 마져 끝내버릴려 했습니다.

**Comment by sween2591** [comment]
PR은 완성하고 날리는 목적도 있지만 팀플할 때는 진행상황 공유를 위한 역할도 있습니다. 실제로 협업할 때 PR에서 커밋마다 코드리뷰를 진행하면서 했을 때가 제일 효율이 잘 나오기도 했었어요,

**Comment by zbqmgldjfh** [comment]
보통 저는 협업할때 하나의 기능이 구현되면 PR을 날리고, 해당 PR을 서로 리뷰한 후 다시 수정하여 merge 하는 방식으로 사용했었습니다.
구현 도중에도 PR을 자주 사용해보도록 하겠습니다.
